- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: myimagedeployment.yaml
      dest: /root/
  - name: delete the previous of kubernetes objects 
    command: kubectl delete -f /root/myimagedeployment.yaml
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /root/myimagedeployment.yaml
